cosmgui/cosmgui/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from codegui import views
#from django.contrib.auth.views import logout as auth_logout

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^accounts/profile/', views.dashboard, name="dashboard"),
    url(r'^$', views.dashboard, name="dashboard"),
    url(r'^login/$', 'django.contrib.auth.views.login',name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^project/(?P<project_id>[0-9]+)$', views.project),
    url(r'^project/(?P<project_id>[0-9]+)/coding$', views.coding, name='coding'),
    url(r'^project/new$', views.new_project),
    url(r'^save/$', views.save),
]

cosmgui/codegui/models.py
from django.db import models
from django.utils import timezone

class Project(models.Model):
    """
    A Project is the container for a set of messages coded by some users.
    When first created (status == New), the daemon spawns a process to
    download the tweets from the list of screennames, then sets the status to
    ready.
    """
    owner = models.ForeignKey('auth.User', null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(default='')
    coders = models.ManyToManyField('auth.User',
                                    related_name='coders',
                                    blank=True)
    authors = models.ManyToManyField('Author')
    created = models.DateTimeField(
            default=timezone.now)
    timespan_start = models.DateField(null=True)
    timespan_end = models.DateField(default=timezone.now)

    NEW = 1
    DOWNLOADING = 2
    READY = 3
    STATUS_CHOICES = (
        (NEW, 'New'),
        (DOWNLOADING, 'Downloading data'),
        (READY, 'Ready'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=NEW)

    def __str__(self):
        return self.name

class Author(models.Model):
    """
    A social media user, identified by the id given by the specific platform.
    """
    username = models.CharField(max_length=200)
    source = models.CharField(max_length=200)

    def __str__(self):
        return self.username

class Message(models.Model):
    """
    A message is a single instance of social media object to code.
    Typical examples of messages are Twitter tweets or Facebook posts.
    """

    project = models.ForeignKey('Project')
    '''
    The metadata of a message are usually included in the content
    (e.g., in the JSON structure returned by the Twitter API)
    but some metadata is kept explicitly in the model for indexing and
    referencing from other models.
    '''
    index = models.IntegerField(default=0) # messages are indexed in order to track the progress
    author = models.ForeignKey('Author')
    source = models.CharField(max_length=200)
    timestamp = models.DateTimeField()
    coded = models.BooleanField(default=False)
    '''
    The content is a blob field of text that could encode XML, JSON etc.,
    depending on the source of the message.
    '''
    content = models.TextField()

    def __str__(self):
        return '[{}] {} {}'.format(self.source,
            self.author,
            self.timestamp)

class Variable(models.Model):
    """
    A variable is one aspect of a message that has to be coded.
    Variables in COSM are always categorical, that is, their value is
    chosen from a fix list of possible choices (categories).
    """
    project = models.ForeignKey('Project')
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name

class Category(models.Model):
    """
    A variable category is one of the possible categories that said
    variable can assume in the coding process.
    """
    variable = models.ForeignKey('Variable')
    value = models.CharField(max_length=200)
    label = models.CharField(max_length=200)

    def __str__(self):
        return "{}: {}".format(self.variable,
            self.label)

class Code(models.Model):
    coder = models.ForeignKey('auth.User')
    message = models.ForeignKey('Message')
    code = models.ForeignKey('Category')
    timestamp = models.DateTimeField(
            default=timezone.now)

    def __str__(self):
        return '{} {} {}'.format(self.timestamp,
            self.coder,
            self.message)

class Progress(models.Model):
    """This model represent the coding status of a project from a particular
    coder's perspective.
    """
    project = models.ForeignKey('Project')
    coder = models.ForeignKey('auth.User')
    index = models.IntegerField(default=0) # the index of the last coded message

    def __str__(self):
        return '{} {} {}'.format(self.project,
            self.coder,
            self.index)

cosmgui/codegui/forms.py
from django.forms import ModelForm
from codegui.models import Project

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name',
                  'description',
                  'coders',
                  'authors',
                  'timespan_start',
                  'timespan_end']

cosmgui/codegui/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from codegui.models import Project, Message, Code, Category, Progress
from django.shortcuts import redirect
from codegui.forms import ProjectForm
from django.db.models import Q

@login_required(login_url='/login/')
def dashboard(request):
    """
    This is the first view activated when users log in.
    It leads to the profile page, or 'dashboard', whose
    content depends on the type of user.
    The admin user will see an overview of all his projects, while
    the coders will see the status of the projects they are involved in.
    """

    '''
    Retrieve the username to pass it to the template.
    The login_required decorator ensures that the username is always present.
    '''
    username = request.user.username

    '''
    Show the project the user is involved in, and the project owned, separately.
    If the user is not authenticated show the login page.
    '''

    # weird syntax to put OR in a query
    projects = Project.objects.all().filter(Q(coders=request.user) | Q(owner=request.user)).distinct()
    #projects = Project.objects.all().filter(coders=request.user)
    #owned = Project.objects.all().filter(owner=request.user)

    return render(request,
                  'codegui/dashboard.html',
                  {'username':username,
                   'projects':projects})

@login_required(login_url='/login/')
def project(request, project_id):
    project = Project.objects.get(pk=project_id)
    coders = project.coders.all()

    # only users assigned to the project can see the project page
    if (not request.user in coders.all()) and (not request.user.is_superuser) :
        return render(request,
                      'codegui/unauthorized.html',
                      {'username':request.user.username,
                       'project':project})

    # get all the messages of the project
    messages = project.message_set.all()
    # count the messages of the project
    n_messages = project.message_set.count()
    # for each message, count 1 if there is at least one code
    # (not sure how efficient/scalable this is)
    n_codes = sum(map(lambda x: int(x.code_set.all().count()>0), messages))

    return render(request,
                  'codegui/project.html', {'project':project,
                                           'coders':coders,
                                           'n_messages':n_messages,
                                           'n_codes':n_codes})

@login_required(login_url='/login/')
def coding(request, project_id):
    project = Project.objects.get(pk=project_id)
    coders = project.coders.all()

    # only users assigned to the project can see the project page
    # TODO this is replicated, find a better way, e.g. a decorator
    if not request.user in coders.all():
        return render(request,
                      'codegui/unauthorized.html',
                      {'username':request.user.username,
                       'project':project})

    # get the next message to code
    try:
        last_index = Progress.objects.get(project=project,
                                          coder=request.user).index
    except (ValueError, Progress.DoesNotExist):
        '''if there is no Progress it means that it is the first time this user
           is coding, therefore a Progress object is created
        '''
        progress = Progress(project=project,
                            coder=request.user,
                            index=0)
        progress.save()

        last_index = 0
    message = project.message_set.get(index=last_index+1)
    variables = project.variable_set.all()
    return render(request,
                  'codegui/coding.html', {'project':project,
                                          'message':message,
                                          'variables':variables})

@login_required(login_url='/login/')
def save(request):
    message = Message.objects.get(id=request.POST["message"])
    project = message.project
    for key, value in request.POST.iteritems():
        if key.startswith("variable_"):
            # create a new code
            code = Code(coder=request.user,
                        message=message,
                        code=Category.objects.get(value=value))
            code.save()

    # update the progress (increase by one)
    progress = Progress.objects.get(project=project,
                                    coder=request.user)
    progress.index = progress.index + 1
    progress.save()

    return redirect("coding", project_id=project.id)


@user_passes_test(lambda u: u.is_superuser)
def new_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('dashboard')
        else:
            print form.errors
            #return redirect('dashboard')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProjectForm()
        return render(request,
                      'codegui/new_project.html',
                      {'form':form})

cosmgui/codegui/templates/codegui/base.html
{% load staticfiles %}
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<title>COSM</title>
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="{% static "css/codegui.css" %}" />
  </head>
  <body>
      <div id="header">
          <h1><a href="/">COSM</a></h1>
      </div>
      <div id="menu">
        {% if request.resolver_match.url_name != 'login' %}
        <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
        {% endif %}
      </div>
      <div class="main">
          {% block content %}
          {% endblock %}
      </div>
  </body>
</html>

cosmgui/codegui/templates/codegui/coding.html
{% extends "codegui/base.html" %}
{% block content %}
<h2>{{project}}</h2>

<p>{{message}}</p>

<p>
<form action="/save/" method="post">
  {% csrf_token %}
  <input type="hidden" name="message" value="{{message.id}}"/>
  {% for variable in variables %}
    <div class="variable">
      <span class="variable_name">{{variable.name}}</span>
      <span class="variable_decription">{{variable.description}}</span>
      {%for category in variable.category_set.all %}
        <div class="category">
          <input type="radio" name="variable_{{variable.id}}" value="{{category.value}}">{{category.label}}</input>
        </div>
      {% endfor %}
    </div>
  {% endfor %}
  <input type="submit" value="submit" />
</form>
</p>

{% endblock content %}

cosmgui/codegui/templates/codegui/dashboard.html
{% extends "codegui/base.html" %}
{% block content %}
<p>
  Welcome {{username}}!
</p>

<h2>Projects:</h2>
</ul>
{% for project in projects %}
    <li>
      {% if project.owner == request.user %}
        <strong>(owner)</strong>
      {% endif %}
      <a href='/project/{{ project.id }}'>{{ project }}</a>
    </li>
{% endfor %}
</ul>

<p>
  <a href="/project/new">Create new project</a>
</p>
{% endblock content%}

cosmgui/codegui/templates/codegui/new_project.html
{% extends "codegui/base.html" %}
{% block content %}
<h2>New Project</h2>

<form action="/project/new" method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <input type="submit" value="submit" />
</form>

{% endblock content %}

cosmgui/codegui/templates/codegui/project.html
{% extends "codegui/base.html" %}
{% block content %}
<h2>{{project}}</h2>
<p>
Coders:
<ul>
  {% for coder in coders %}
  <li>{{coder}}, {{coder.email}}</li>
  {% endfor %}
</ul>

</p>

<p>
  Progress: {{n_codes}}/{{n_messages}}
</p>

<p>
  <a href='/project/{{ project.id }}/coding'>continue coding</a>
</p>


{% endblock content %}

cosmgui/codegui/templates/codegui/unauthorized.html
{% extends "codegui/base.html" %}
{% block content %}
<p>
  User {{username}} is not authorized to access project {{ project }}.
</p>

<p>
  <a href='/'>Main page</a>
</p>
{% endblock content%}